[context.production.environment]
HUGO_VERSION = "0.37"


[context.deploy-preview.environment]
HUGO_VERSION = "0.37"



[build]
publish = "public"
command = "hugo"

[[redirects]]
  from = "https://ro-nav-community.netlify.com/*"
  to = "https://navhub.org/:splat"
  status = 301
  force = true # COMMENT: ensure that we always redirect
